### PR TITLE
Document architectural decisions

### PR DESCRIPTION
**Pull request by thatbudakguy**
- Add ADR template
- Propose usage of ADR, via ADR

### CODE REVIEW

**Review by rlskoeser — COMMENTED** [review]
I'm ok with adopting ADR for this repo, and the template looks pretty useful.

I think we need a little more documentation somewhere — in the readme? or a readme in the adr folder, maybe? Would be nice to have information like: what is this, link to ADR documentation, brief notes about how or when to add one,  naming conventions

**Review by kmcelwee — APPROVED** [review]
I'm not sure I agree that this is equated with a changelog, if anything I'd still recommend keeping a changelog in addition to this (if you're interested, PUL operates mostly off one branch, and just has a test that checks that their `changelog.md` has changed when merging a branch into `main`)

**Comment by thatbudakguy** [comment]
@kmcelwee is there a changelog for https://github.com/pulibrary/princeton_ansible? the issue is that we don't do releases for this repo, so I'm not sure how to group changelog entries/when to add them.

**Comment by thatbudakguy** [comment]
Added some more info about the ADR spec to the main README, thx for the reminder @rlskoeser

**Comment by kmcelwee** [comment]
@thatbudakguy Nope 🤷 For DRDS, each ticket is attached to a branch off main. Changes for each PR are then logged in Changelog with a date.

**Comment by thatbudakguy** [comment]
@rlskoeser OK to merge this? I think since PUL doesn't use a CHANGELOG for their ansible repo, we can stick with ADR only for now.

**Comment by rlskoeser** [comment]
@thatbudakguy yes, readme updates look good. Thanks for adding the documentation.

**Pull request merged**
